site_name: CosimGym Documentation
site_description: Documentation for CosimGym, a co-simulation framework for reinforcement learning 
theme:
  name: material
  logo: images/cosimgym_icon_transparent.svg
  favicon: images/cosimgym_icon_transparent.svg
  palette:
    primary: teal
  hljs_languages:
    - yaml

nav:
  - Home: index.md
  - Installation: Installation_Setup.md
  - Overview: 
    - Introduction: overview/introduction.md
    - Core Concepts: overview/core_concepts.md
    - Terminology: overview/terminology.md
    - Architecture: overview/architecture.md
  - User Guide:
    - Getting Started: user_guide/getting_started.md
    - Scenario Configuration:
      - Overview: user_guide/scenario_configuration/overview.md
      - General Configuration: user_guide/scenario_configuration/general.md
      - Federation Configuration: user_guide/scenario_configuration/federation.md
      - Federate Configuration: user_guide/scenario_configuration/federate.md
      - Reinforcement Learning Configuration: user_guide/scenario_configuration/rl.md
    - Custom Models & Catalog: user_guide/custom_models.md
    - Reinforcement Learning Integration: user_guide/rl_integration.md
    - Dashboard & Analytics: user_guide/dashboard.md
  - Examples: 
    - Examples List: examples/examples_list.md
    - Example 1 (Base Simulation): examples/example_base.md
    - Example 2 (RL Training): examples/example_rl.md
