# Example Federation Configuration YAML
# This file demonstrates the structure needed to instantiate a FederationConfig object



version: "1.0.0"
name: "simple_test_SACsb3"
scenario_description: test using integration of SB3 SAC algorithm.

start_time: "2024-01-01T00:00:00"
end_time: "2024-01-01T01:00:00"
log_level: DEBUG

memory_config:
  batch_size: 100
  attrs: ["position", "velocity", "acceleration", "force", "disturbance"]


# TODO: add influxdb configs

reinforcement_learning_config:
  seed: 42
  environment:
    observations:
      federation_1.spring_federate.0.position: null
      federation_1.spring_federate.0.velocity: null
      federation_1.spring_federate.0.acceleration: null
    actions:
      federation_1.spring_federate.0.force: null
  agent:
    model_name: rl_simple_SACsb3
    backend: stable_baselines3
    algorithm: SAC
    hyperparameters:
      gamma: 0.99
      batch_size: 64
      learning_rate: 0.001
      train_frequency: 1
      gradient_steps: 1
    params:
      gradient_clip: 10.0
      target_update_interval: 5
      replay_buffer:
        buffer_size: 100000
        prefill_steps: 5
  run:
    train:
      episodes: 10
      episode_length: 10
    test:
      episodes: 1
      episode_length: 10
      deterministic: true
      checkpoint: None
  experiment:
    checkpoint:
      best: best_sac_sb3_model.pth
federations:
  federation_1:
    broker_config:
      core_type: "tcp"
      port: 23404
      federates: 1
      log_level: DEBUG

    federate_configs:
      spring_federate:
          name: "spring_federate"
          type: "base"
          log_level: DEBUG
          core_name: "fed1"
          core_type: "zmq"  
          
          timing_configs:
            real_period: 1  
            
          flags:
            terminate_on_error: true
            wait_for_current_time_update: true
        
          connections:
            endpoints: []
            subscribes:
              - key: "force"
                type: "double"
                units: "N"
             
            publishes:
              - key: "position"
                type: "double"
                units: "m"
              - key: "velocity"
                type: "double"
                units: "m/s"
              - key: "acceleration"
                type: "double"
                units: "m/s^2"

          model_configs:
            instantiation:
              model_name: "spring_mass_damper"
              n_instances: 1
              prefix: "spring"
              parallel_execution: false
            
            parameters:
              mass: 5.0
              damping: 2.0
              stiffness: 10.0
            
            init_state:
              force: 0.0
              disturbance: 0.0
              position: 0.0
              velocity: 0.0
              acceleration: 0.0
            
            user_defined:
              solver: "euler"
              integrator: "fixed-step"
  
   