# Example Federation Configuration YAML
# This file demonstrates the structure needed to instantiate a FederationConfig object



version: "1.0.0"
scenario_name: "simple_test_rlagent"
scenario_description: A simple test, only one federation but using a yaml with open config for multiple.

start_time: "2024-01-01T00:00:00"
end_time: "2024-01-01T01:00:00"
log_level: DEBUG

memory_config:
  batch_size: 100
  attrs: ["position", "velocity", "acceleration", "force", "disturbance"]


# TODO: add influxdb configs

reinforcement_learning_config:

  # RLAgentConfig – which agent class to load
  agent:
    model_name: "rl_simple_agent"             # class inside that module
    env:
      observations: [federation_1.spring_federate.0.position, federation_1.spring_federate.0.velocity, federation_1.spring_federate.0.acceleration]  # list of keys to use as observations
      actions: [federation_1.spring_federate.0.force ]  # list of actions
      action_spaces_type: ["discrete"] # list of action space types corresponding to the actions (only discrete, box) MUST have same lenght of actions
      action_space_remapping: [[-10,10]] # list of action space remapping corresponding to the actions (for discrete only)
      include_prev_obs: [0,0,0]  # how many previous observations to include in the state representation (0 for none) must be None or same lenght of observations
      

  # RLTrainingConfig – core training loop settings
  training:
    mode:                 "online"   # online | offline | mixed
    episode_length:       5       # total simulation steps per episode
    n_episodes: 10       # max agent steps before forced reset


# WHEN doing RL the controlled federate will not specify targets,
#  these will be filled by the Scenario manager
  
federations:
  federation_1:
    broker_config:
      core_type: "tcp"
      port: 23404
      federates: 1
      log_level: DEBUG

    federate_configs:
      spring_federate:
          name: "spring_federate"
          type: "base"
          log_level: DEBUG
          core_name: "fed1"
          core_type: "zmq"  
          
          timing_configs:
            real_period: 1  
            
          flags:
            terminate_on_error: true
            wait_for_current_time_update: true
        
          connections:
            endpoints: []
            subscribes:
              - key: "force"
                type: "double"
                units: "N"
             
            publishes:
              - key: "position"
                type: "double"
                units: "m"
              - key: "velocity"
                type: "double"
                units: "m/s"
              - key: "acceleration"
                type: "double"
                units: "m/s^2"

          model_configs:
            instantiation:
              model_name: "spring_mass_damper"
              n_instances: 1
              prefix: "spring"
              parallel_execution: false
            
            parameters:
              mass: 5.0
              damping: 2.0
              stiffness: 10.0
            
            init_state:
              force: 10.0
              disturbance: 0.0
              position: 0.0
              velocity: 0.0
              acceleration: 0.0
            
            user_defined:
              solver: "euler"
              integrator: "fixed-step"
  
   