# Example Federation Configuration YAML
# This file demonstrates the structure needed to instantiate a FederationConfig object



version: "1.0.0"
name: "simple_test_DQN"
scenario_description: A simple test, only one federation but using a yaml with open config for multiple.

start_time: "2024-01-01T00:00:00"
end_time: "2024-01-01T01:00:00"
log_level: DEBUG

memory_config:
  batch_size: 100
  attrs: ["position", "velocity", "acceleration", "force", "disturbance"]



reinforcement_learning_config:
  environment:
    observations:
      federation_1.spring_federate.0.position:
        causality: next_step
      federation_1.spring_federate.0.velocity:
        causality: next_step
      federation_1.spring_federate.0.acceleration:
        causality: next_step
    actions:
      federation_1.spring_federate.0.force:
        space: discrete
        bins: 5
    reward: models.model_catalog.RL_agents.reward_functions.spring_oscillation_reward
  agent:
    model_name: rl_simple_DQN
    backend: custom_torch
    algorithm: DQN
    hyperparameters:
      gamma: 0.99
      batch_size: 64
      learning_rate: 0.001
    params:
      gradient_clip: 10.0
      target_update_interval: 100
      exploration:
        strategy: epsilon_greedy
        initial_epsilon: 1.0
        final_epsilon: 0.05
        epsilon_decay_steps: 5000
      replay_buffer:
        buffer_size: 100000
        prefill_steps: 1000
  run:
    train:
      episodes: 1000
      episode_length: 100
    test:
      episodes: 1
      episode_length: 100
      deterministic: true
federations:
  federation_1:
    broker_config:
      core_type: "tcp"
      port: 23404
      federates: 1
      log_level: DEBUG

    federate_configs:
      spring_federate:
          name: "spring_federate"
          type: "base"
          log_level: DEBUG
          core_name: "fed1"
          core_type: "zmq"  
          
          timing_configs:
            real_period: 1  
            
            
          flags:
            terminate_on_error: true
            wait_for_current_time_update: true
        
          connections:
            endpoints: []
            subscribes:
              - key: "force"
                type: "double"
                units: "N"
             
            publishes:
              - key: "position"
                type: "double"
                units: "m"
              - key: "velocity"
                type: "double"
                units: "m/s"
              - key: "acceleration"
                type: "double"
                units: "m/s^2"

          model_configs:
            instantiation:
              model_name: "spring_mass_damper"
              n_instances: 1
              prefix: "spring"
              parallel_execution: false
            
            parameters:
              mass: 5.0
              damping: 2.0
              stiffness: 10.0
            
            init_state:
              force: 0.0
              disturbance: 0.0
              position: 0.0
              velocity: 0.0
              acceleration: 0.0
            
            user_defined:
              solver: "euler"
              integrator: "fixed-step"
  
   